import { ItemCard } from '@/components/ItemCard'
import { Button } from '@/components/ui/button'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useAccount, useConnect, useDisconnect } from 'wagmi'
import { InjectedConnector } from 'wagmi/connectors/injected'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { address, isConnected } = useAccount()
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  })
  const { disconnect } = useDisconnect()

  // const accessDB = async () => {
  //   if (walletClient) {
  //     const db = new Database({ signer: walletClient })
  //   }
  // }

  if (isConnected)
    return (
      <div>
        Connected to {address}
        <button onClick={() => disconnect()}>Disconnect</button>
      </div>
    )

  return (
    <>
      <Head>
        <title>Next Boilerplate by Spheron</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full flex-col">
        {/* Nav bar */}
        <div className="flex w-full flex-row items-center justify-between border px-6 py-4">
          <div className="flex w-full flex-row gap-2">
            <div className="flex flex-row pr-4">
              <div className="p-1">
                <Image
                  src="/gamevault_transparent.png"
                  alt="logo"
                  width={'20'}
                  height={'20'}
                />
              </div>
              <div className="pl-0 text-lg font-bold">GameVault</div>
            </div>
            <Link className="hover:text-blue-700" href={'/'}>
              Marketplace
            </Link>
            <Link className="hover:text-blue-700" href={'/dashboard'}>
              Dashboard
            </Link>
          </div>
          <Button>Connect</Button>
        </div>

        {/* Home content */}
        <div className="container flex min-h-[calc(100vh-264px)] w-full flex-col items-center justify-center gap-4">
          <h1 className="scroll-m-20 p-8 text-4xl font-extrabold tracking-tight lg:text-5xl">
            Best Game assets always available
          </h1>
          <div className="text-lg font-semibold">
            Build your game with the best AI generated game assets
          </div>

          <div className="flex w-full flex-row justify-between pt-20">
            <ItemCard />
            <ItemCard />
            <ItemCard />
          </div>
        </div>
      </main>
    </>
  )
}
