import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useAccount, useConnect, useDisconnect, useWalletClient } from 'wagmi'
import { InjectedConnector } from 'wagmi/connectors/injected'
import { Database } from '@tableland/sdk'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { address, isConnected } = useAccount()
  const { data: walletClient } = useWalletClient()
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  })
  const { disconnect } = useDisconnect()

  // const accessDB = async () => {
  //   if (walletClient) {
  //     const db = new Database({ signer: walletClient })
  //   }
  // }

  if (isConnected)
    return (
      <div>
        Connected to {address}
        <button onClick={() => disconnect()}>Disconnect</button>
      </div>
    )

  return (
    <>
      <Head>
        <title>Next Boilerplate by Spheron</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Hello World</p>
        <button onClick={() => connect()}>Connect Wallet</button>
      </main>
    </>
  )
}
