import { useDB } from '@/hooks/use-db'
import { upload } from '@spheron/browser-upload'
import Head from 'next/head'
import { useForm } from 'react-hook-form'
import { useAccount } from 'wagmi'

type FormValues = {
  name: string
  description: string
  files: FileList
}

export default function Home() {
  const { address, isConnected } = useAccount()
  const { myFiles, saveFile } = useDB()
  console.log('🚀 ~ file: upload.tsx:16 ~ Home ~ myFiles:', myFiles)

  const { register, handleSubmit } = useForm<FormValues>()

  const uploadFile = async (files: File[]) => {
    const response = await fetch(`/api/token`) // get the temporary access token from server
    const resJson = await response.json()
    const token = resJson.uploadToken

    let currentlyUploaded = 0

    const { uploadId, bucketId, protocolLink, dynamicLinks } = await upload(files, {
      token,
      onChunkUploaded: (uploadedSize, totalSize) => {
        currentlyUploaded += uploadedSize
        console.log(`Uploaded ${currentlyUploaded} of ${totalSize} Bytes.`)
      },
    })
    console.log(
      '🚀 ~ file: upload.tsx:28 ~ uploadFile ~ uploadId, bucketId, protocolLink, dynamicLinks:',
      uploadId,
      bucketId,
      protocolLink,
      dynamicLinks
    )
  }

  const onSubmit = (data: FormValues) => {
    console.log('🚀 ~ file: upload.tsx:31 ~ onSubmit ~ data:', data)
    const fileListArray = Array.from(data.files)

    uploadFile(fileListArray)
  }

  return (
    <>
      <Head>
        <title>Next Boilerplate by Spheron</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Hello World</p>
        <form onSubmit={handleSubmit(onSubmit)}>
          <label htmlFor="name">Name</label>
          <input defaultValue="test" {...register('name')} />

          <label htmlFor="files">File</label>
          <input type="file" id="files" {...register('files')} />
          <input type="submit" />
        </form>

        <h2 className="mb-4 text-lg font-medium text-gray-800">Portfolio</h2>
        <div className="grid grid-cols-3 gap-4">
          {/* {myFiles?.map((file) => (
            <FileGridItem fileData={file.data} />
          ))} */}
        </div>
      </main>
    </>
  )
}
